config-server:
  build: config-server
  environment:
   - environment=docker
  ports:
   - "9090:9090"
  expose:
   - "9090"

discovery-service:
  build: discovery-service
  environment:
   - environment=docker
  ports:
   - "8761:8761"
  expose:
   - "8761"
  links:
   - config-server


edge-server:
  build: edge-server
  environment:
   - environment=docker
  ports:
   - "8765:8765"
  expose:
   - "8765"
  links:
   - config-server
   - discovery-service
    
card:
  build: card-service
  environment:
   - environment=docker
  expose:
   - "8080"
  links:
   - config-server
   - discovery-service
   
statement:
  build: statement-service
  environment:
   - environment=docker
  expose:
   - "8080"
  links:
   - config-server
   - discovery-service

card-statement:
  build: card-statement-composite
  environment:
   - environment=docker
  expose:
   - "8080"
  links:
   - config-server
   - discovery-service
   - card
   - statement

monitor:
  build: monitor-dashboard
  environment:
   - environment=docker
  ports:
   - "8179:8179"
  expose:
   - "8179"
  links:
   - config-server  
   - discovery-service
 
turbine:
  build: turbine
  environment:
   - environment=docker
  ports:
   - "8989:8989"
  expose:
   - "8989"
  links:
   - config-server  
   - discovery-service
